name: Build Docker Image

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Container Registry
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }} # Or GHCR_USERNAME
#          password: ${{ secrets.DOCKER_PASSWORD }} # Or GHCR_TOKEN

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/gnu-sdk:latest # Replace with your image name and tag
